In [132]:
!pip install optuna
from google.colab import drive
import pandas as pd
import numpy as np
from sklearn.model_selection import KFold
from xgboost import XGBClassifier
import optuna
from sklearn.metrics import (accuracy_score, precision_score,
                            recall_score, f1_score, roc_auc_score)
import sklearn
sklearn.set_config(transform_output="pandas")

# Mount the drive to access files
drive.mount('/content/drive')

Collecting optuna
  Downloading optuna-4.3.0-py3-none-any.whl.metadata (17 kB)
Collecting alembic>=1.5.0 (from optuna)
  Downloading alembic-1.15.2-py3-none-any.whl.metadata (7.3 kB)
Collecting colorlog (from optuna)
  Downloading colorlog-6.9.0-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (from optuna) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from optuna) (24.2)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.11/dist-packages (from optuna) (2.0.40)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (from optuna) (4.67.1)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.11/dist-packages (from optuna) (6.0.2)
Requirement already satisfied: Mako in /usr/lib/python3/dist-packages (from alembic>=1.5.0->optuna) (1.1.3)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.11/dist-packages (from alembic>=1.5.0->optuna) (4.13.2)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.11/dist-packages (from sqlalchemy>=1.4.2->optuna) (3.2.1)
Downloading optuna-4.3.0-py3-none-any.whl (386 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 386.6/386.6 kB 7.1 MB/s eta 0:00:00
Downloading alembic-1.15.2-py3-none-any.whl (231 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 231.9/231.9 kB 13.5 MB/s eta 0:00:00
Downloading colorlog-6.9.0-py3-none-any.whl (11 kB)
Installing collected packages: colorlog, alembic, optuna
Successfully installed alembic-1.15.2 colorlog-6.9.0 optuna-4.3.0
Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [3]:
# Load data
dir_path = '/content/drive/My Drive/Colab Notebooks/Spaceship Titanic/'
file_path = dir_path + 'train.csv'
train_data = pd.read_csv(file_path)

file_path = dir_path + 'test.csv'
test_data = pd.read_csv(file_path)

print(f"Train shape: {train_data.shape}, Test shape: {test_data.shape}")

Train shape: (8693, 14), Test shape: (4277, 13)

In [107]:
# Convert Transported into int
train_data['Transported'] = train_data['Transported'].astype(int)

train_data['dataset'] = 'train'
test_data['dataset'] = 'test'

data = pd.concat([train_data, test_data]).reset_index(drop=True)
data.head()

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported,dataset
0,0001_01,Europa,False,B/0/P,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0,Maham Ofracculy,0.0,train
1,0002_01,Earth,False,F/0/S,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,Juanna Vines,1.0,train
2,0003_01,Europa,False,A/0/S,TRAPPIST-1e,58.0,True,43.0,3576.0,0.0,6715.0,49.0,Altark Susent,0.0,train
3,0003_02,Europa,False,A/0/S,TRAPPIST-1e,33.0,False,0.0,1283.0,371.0,3329.0,193.0,Solam Susent,0.0,train
4,0004_01,Earth,False,F/1/S,TRAPPIST-1e,16.0,False,303.0,70.0,151.0,565.0,2.0,Willy Santantines,1.0,train

In [108]:
# Parse Cabin = deck/num/side
data['cabin_deck'] = data['Cabin'].str.split('/').str[0]
data['cabin_num'] = data['Cabin'].str.split('/').str[1]
data['cabin_side'] = data['Cabin'].str.split('/').str[2]

In [109]:
data.isna().sum()

PassengerId        0
HomePlanet       288
CryoSleep        310
Cabin            299
Destination      274
Age              270
VIP              296
RoomService      263
FoodCourt        289
ShoppingMall     306
Spa              284
VRDeck           268
Name             294
Transported     4277
dataset            0
cabin_deck       299
cabin_num        299
cabin_side       299
dtype: int64

In [110]:
# Handle Missing Values

# Define numerical and categorical columns
numerical_col_list = ['Age', 'RoomService', 'FoodCourt', 'ShoppingMall', 'Spa', 'VRDeck']
categorical_col_list = ['HomePlanet', 'CryoSleep', 'Destination', 'VIP', 'cabin_side', 'Name']

# Fill numerical columns with median
for col in numerical_col_list:
    data[col] = data[col].fillna(data[col].median())

# Fill categorical columns with mode
for col in categorical_col_list:
    data[col] = data[col].fillna(data[col].mode()[0])

# Cabin Deck: fill with mode by HomePlanet & Destination
data['cabin_deck'] = data.groupby(['HomePlanet', 'Destination'])['cabin_deck'].transform(lambda x: x.fillna(x.mode()[0]))

<ipython-input-110-563302df63ce>:13: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data[col] = data[col].fillna(data[col].mode()[0])

In [111]:
# Feature Engineering

# Passenger group count
data['passenger_group'] = data['PassengerId'].str.split('_').str[0]
data['passenger_group_count'] = data.groupby('passenger_group')['PassengerId'].transform('count')

# One-hot encoding: HomePlanet, Destination, cabin_deck, cabin_side
data = pd.get_dummies(data, columns=['HomePlanet', 'Destination', 'cabin_deck', 'cabin_side'],
                      prefix=['homeplanet', 'destination', 'deck', 'side'])

In [112]:
data.columns

Index(['PassengerId', 'CryoSleep', 'Cabin', 'Age', 'VIP', 'RoomService',
       'FoodCourt', 'ShoppingMall', 'Spa', 'VRDeck', 'Name', 'Transported',
       'dataset', 'cabin_num', 'passenger_group', 'passenger_group_count',
       'homeplanet_Earth', 'homeplanet_Europa', 'homeplanet_Mars',
       'destination_55 Cancri e', 'destination_PSO J318.5-22',
       'destination_TRAPPIST-1e', 'deck_A', 'deck_B', 'deck_C', 'deck_D',
       'deck_E', 'deck_F', 'deck_G', 'deck_T', 'side_P', 'side_S'],
      dtype='object')

In [113]:
# Features
feature_list = ['CryoSleep', 'Age', 'VIP', 'RoomService', 'FoodCourt',
                'ShoppingMall', 'Spa', 'VRDeck', 'passenger_group_count'
                ] + \
                list(data.columns[data.columns.str.startswith('homeplanet')]) + \
                list(data.columns[data.columns.str.startswith('destination')]) + \
                list(data.columns[data.columns.str.startswith('deck')]) + \
                list(data.columns[data.columns.str.startswith('side')])
feature_list

['CryoSleep',
 'Age',
 'VIP',
 'RoomService',
 'FoodCourt',
 'ShoppingMall',
 'Spa',
 'VRDeck',
 'passenger_group_count',
 'homeplanet_Earth',
 'homeplanet_Europa',
 'homeplanet_Mars',
 'destination_55 Cancri e',
 'destination_PSO J318.5-22',
 'destination_TRAPPIST-1e',
 'deck_A',
 'deck_B',
 'deck_C',
 'deck_D',
 'deck_E',
 'deck_F',
 'deck_G',
 'deck_T',
 'side_P',
 'side_S']

In [114]:
# Split train & test data
new_train_data = data[data['dataset'] == 'train'].copy()
new_test_data = data[data['dataset'] == 'test'].reset_index(drop=True).copy()

In [136]:
# Prepare features and target variable
X = new_train_data[feature_list]
y = new_train_data['Transported']

# Prepare test data
X_test = new_test_data[feature_list]

X.shape

(8693, 25)

In [137]:
# Initialize XGBoost parameters
# Use optuna to find the best hyperparameters
params = {
    'objective': 'binary:logistic',
    'eval_metric': 'logloss',
    'n_estimators': 1400,
    'learning_rate': 0.04931476093184571,
    'max_depth': 4,
    'subsample': 0.6578843387359619,
    'colsample_bytree': 0.6902394255031622,
    'gamma': 0.11174367093570015,
    'random_state': 0,
    'early_stopping_rounds': 50
}

# Store results
metrics = {
    'accuracy': [],
    'precision': [],
    'recall': [],
    'f1': [],
    'roc_auc': []
}

# Training model
n_splits=5
kf = KFold(n_splits=n_splits)

for fold, (train_idx, val_idx) in enumerate(kf.split(X, y), 1):
    print(f"\nFold {fold}/{n_splits}")

    # Split data
    X_train, X_val = X.iloc[train_idx], X.iloc[val_idx]
    y_train, y_val = y.iloc[train_idx], y.iloc[val_idx]

    # Initialize and train model
    model = XGBClassifier(**params)
    model.fit(
        X_train, y_train,
        eval_set=[(X_val, y_val)],
        verbose=50,

    )

    # Predictions
    y_pred = model.predict(X_val)
    y_proba = model.predict_proba(X_val)
    y_proba = y_proba[:, 1]

    # Calculate metrics
    metrics['accuracy'].append(accuracy_score(y_val, y_pred))
    metrics['precision'].append(precision_score(y_val, y_pred, average='weighted'))
    metrics['recall'].append(recall_score(y_val, y_pred, average='weighted'))
    metrics['f1'].append(f1_score(y_val, y_pred, average='weighted'))

    # ROC AUC (handle multi-class)
    if len(np.unique(y)) > 2:
        metrics['roc_auc'].append(roc_auc_score(y_val, y_proba, multi_class='ovo'))
    else:
        metrics['roc_auc'].append(roc_auc_score(y_val, y_proba))

# Print results
print("\nFinal Metrics Across All Folds:")
for metric, values in metrics.items():
    print(f"{metric.capitalize()}: {np.mean(values):.4f} ± {np.std(values):.4f}")

Fold 1/5
[0]	validation_0-logloss:0.67815
[50]	validation_0-logloss:0.46153
[100]	validation_0-logloss:0.44087
[150]	validation_0-logloss:0.43656
[200]	validation_0-logloss:0.43482
[250]	validation_0-logloss:0.43355
[300]	validation_0-logloss:0.43231
[324]	validation_0-logloss:0.43284

Fold 2/5
[0]	validation_0-logloss:0.67912
[50]	validation_0-logloss:0.45450
[100]	validation_0-logloss:0.43311
[150]	validation_0-logloss:0.42827
[200]	validation_0-logloss:0.42466
[250]	validation_0-logloss:0.42369
[300]	validation_0-logloss:0.42168
[350]	validation_0-logloss:0.42179
[400]	validation_0-logloss:0.42230
[407]	validation_0-logloss:0.42164

Fold 3/5
[0]	validation_0-logloss:0.67908
[50]	validation_0-logloss:0.45815
[100]	validation_0-logloss:0.43410
[150]	validation_0-logloss:0.42417
[200]	validation_0-logloss:0.42265
[250]	validation_0-logloss:0.41963
[300]	validation_0-logloss:0.41948
[350]	validation_0-logloss:0.41939
[391]	validation_0-logloss:0.41977

Fold 4/5
[0]	validation_0-logloss:0.67969
[50]	validation_0-logloss:0.45158
[100]	validation_0-logloss:0.42530
[150]	validation_0-logloss:0.41902
[200]	validation_0-logloss:0.41647
[250]	validation_0-logloss:0.41435
[300]	validation_0-logloss:0.41349
[332]	validation_0-logloss:0.41360

Fold 5/5
[0]	validation_0-logloss:0.67728
[50]	validation_0-logloss:0.43248
[100]	validation_0-logloss:0.40810
[150]	validation_0-logloss:0.40043
[200]	validation_0-logloss:0.39837
[250]	validation_0-logloss:0.39759
[292]	validation_0-logloss:0.39820

Final Metrics Across All Folds:
Accuracy: 0.8041 ± 0.0119
Precision: 0.8100 ± 0.0100
Recall: 0.8041 ± 0.0119
F1: 0.8042 ± 0.0122
Roc_auc: 0.8916 ± 0.0083

In [138]:
# Create feature importance DataFrame with proper names
feature_importances = pd.DataFrame({
    'feature': feature_list,
    'importance': model.feature_importances_  # Or mean_importances from cross-val
}).sort_values('importance', ascending=False)

# Display with clean formatting
print("\nFeature Importances:")
print(feature_importances.to_string(index=False))

Feature Importances:
                  feature  importance
                CryoSleep    0.418519
                   deck_G    0.059196
         homeplanet_Earth    0.058088
        homeplanet_Europa    0.050989
                      Spa    0.036990
                   deck_E    0.034678
              RoomService    0.033075
                   deck_F    0.032002
                   VRDeck    0.030620
                   side_S    0.024708
          homeplanet_Mars    0.023707
                FoodCourt    0.022825
                   side_P    0.022003
                   deck_B    0.020825
                   deck_C    0.019460
             ShoppingMall    0.019050
  destination_55 Cancri e    0.014825
                      Age    0.013722
destination_PSO J318.5-22    0.012148
                   deck_A    0.011528
  destination_TRAPPIST-1e    0.011496
                   deck_D    0.010768
    passenger_group_count    0.010257
                      VIP    0.008522
                   deck_T    0.000000

In [139]:
# Final model training
params = {
    'objective': 'binary:logistic',  # Change for multi-class
    'n_estimators': 1400,
    'learning_rate': 0.04931476093184571,
    'max_depth': 4,
    'subsample': 0.6578843387359619,
    'colsample_bytree': 0.6902394255031622,
    'gamma': 0.11174367093570015,
    'random_state': 0
}

final_model = XGBClassifier(**params)
final_model.fit(X, y)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.6902394255031622, device=None,
              early_stopping_rounds=None, enable_categorical=False,
              eval_metric=None, feature_types=None, gamma=0.11174367093570015,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.04931476093184571,
              max_bin=None, max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=4, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=1400, n_jobs=None,
              num_parallel_tree=None, random_state=0, ...)

In [140]:
# Prepare submission
test_preds = final_model.predict(X_test)

# Convert 0 or 1 into FALSE or TRUE
test_preds = test_preds.astype(bool)

submission_data = pd.DataFrame({
    'PassengerId': new_test_data['PassengerId'],
    'Transported': test_preds
})
submission_data.to_csv(dir_path+'final_submission_v2.csv', index=False)

In [134]:
# # Find the best hyperparameters

# ## Define the objective function for Optuna
# def objective(trial):
#     params = {
#         'objective': 'binary:logistic',
#         'eval_metric': 'logloss',
#         'n_estimators': trial.suggest_int('n_estimators', 100, 2000, step=100),
#         'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.2),
#         'max_depth': trial.suggest_int('max_depth', 3, 15),
#         'subsample': trial.suggest_uniform('subsample', 0.6, 1.0),
#         'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.6, 1.0),
#         'gamma': trial.suggest_uniform('gamma', 0, 1),
#         'random_state': 0,
#         'early_stopping_rounds': 50
#     }

#     # Store the results for each fold
#     metrics = {
#         'accuracy': [],
#         'precision': [],
#         'recall': [],
#         'f1': [],
#         'roc_auc': []
#     }

#     # Cross-validation
#     n_splits = 5
#     kf = KFold(n_splits=n_splits)

#     for fold, (train_idx, val_idx) in enumerate(kf.split(X, y), 1):
#         print(f"\nFold {fold}/{n_splits}")

#         # Split data
#         X_train, X_val = X.iloc[train_idx], X.iloc[val_idx]
#         y_train, y_val = y.iloc[train_idx], y.iloc[val_idx]

#         # Initialize and train the model
#         model = XGBClassifier(**params)
#         model.fit(
#             X_train, y_train,
#             eval_set=[(X_val, y_val)],
#             verbose=0,
#         )

#         # Predictions
#         y_pred = model.predict(X_val)
#         y_proba = model.predict_proba(X_val)
#         y_proba = y_proba[:, 1]

#         # Calculate metrics
#         metrics['accuracy'].append(accuracy_score(y_val, y_pred))
#         metrics['precision'].append(precision_score(y_val, y_pred, average='weighted'))
#         metrics['recall'].append(recall_score(y_val, y_pred, average='weighted'))
#         metrics['f1'].append(f1_score(y_val, y_pred, average='weighted'))

#         # ROC AUC (handle multi-class)
#         if len(np.unique(y)) > 2:
#             metrics['roc_auc'].append(roc_auc_score(y_val, y_proba, multi_class='ovo'))
#         else:
#             metrics['roc_auc'].append(roc_auc_score(y_val, y_proba))

#     # Return the metric you want to optimize; here, we use the F1-score
#     return np.mean(metrics['f1'])

# # Create a study to optimize the hyperparameters
# study = optuna.create_study(direction='maximize')  # 'maximize' for optimization metrics like accuracy, f1, etc.
# study.optimize(objective, n_trials=100)  # Run 100 trials

# # Output the best hyperparameters
# print("Best hyperparameters found: ", study.best_params)

# # You can also print the best value for the objective
# print("Best F1 score: ", study.best_value)

[I 2025-04-28 15:11:11,015] A new study created in memory with name: no-name-eea9a415-d907-4ff9-9953-94683cc4ea84
<ipython-input-134-1caae69baf53>:9: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.2),
<ipython-input-134-1caae69baf53>:11: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:12: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:13: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'gamma': trial.suggest_uniform('gamma', 0, 1),

Fold 1/5

Fold 2/5

Fold 3/5

Fold 4/5

Fold 5/5

[I 2025-04-28 15:11:16,372] Trial 0 finished with value: 0.8026503196664804 and parameters: {'n_estimators': 1100, 'learning_rate': 0.10752431956969061, 'max_depth': 4, 'subsample': 0.8231221435744875, 'colsample_bytree': 0.7244682734079122, 'gamma': 0.7476367454901625}. Best is trial 0 with value: 0.8026503196664804.
<ipython-input-134-1caae69baf53>:9: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.2),
<ipython-input-134-1caae69baf53>:11: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:12: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:13: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'gamma': trial.suggest_uniform('gamma', 0, 1),

Fold 1/5

Fold 2/5

Fold 3/5

Fold 4/5

Fold 5/5

[I 2025-04-28 15:11:21,139] Trial 1 finished with value: 0.7953402745765932 and parameters: {'n_estimators': 600, 'learning_rate': 0.16044569225929964, 'max_depth': 9, 'subsample': 0.6554512452963498, 'colsample_bytree': 0.8282877031602639, 'gamma': 0.5394008008548054}. Best is trial 0 with value: 0.8026503196664804.
<ipython-input-134-1caae69baf53>:9: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.2),
<ipython-input-134-1caae69baf53>:11: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:12: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:13: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'gamma': trial.suggest_uniform('gamma', 0, 1),

Fold 1/5

Fold 2/5

Fold 3/5

Fold 4/5

Fold 5/5

[I 2025-04-28 15:11:25,265] Trial 2 finished with value: 0.797305011080959 and parameters: {'n_estimators': 1400, 'learning_rate': 0.04714122231634861, 'max_depth': 9, 'subsample': 0.8057805425753404, 'colsample_bytree': 0.8988519222601642, 'gamma': 0.27570446810922933}. Best is trial 0 with value: 0.8026503196664804.
<ipython-input-134-1caae69baf53>:9: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.2),
<ipython-input-134-1caae69baf53>:11: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:12: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:13: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'gamma': trial.suggest_uniform('gamma', 0, 1),

Fold 1/5

Fold 2/5

Fold 3/5

Fold 4/5

Fold 5/5

[I 2025-04-28 15:11:28,433] Trial 3 finished with value: 0.7956017087469334 and parameters: {'n_estimators': 2000, 'learning_rate': 0.0869477829137335, 'max_depth': 13, 'subsample': 0.9490814634304803, 'colsample_bytree': 0.7603375730444404, 'gamma': 0.43008065330618694}. Best is trial 0 with value: 0.8026503196664804.
<ipython-input-134-1caae69baf53>:9: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.2),
<ipython-input-134-1caae69baf53>:11: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:12: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:13: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'gamma': trial.suggest_uniform('gamma', 0, 1),

Fold 1/5

Fold 2/5

Fold 3/5

Fold 4/5

Fold 5/5

[I 2025-04-28 15:11:40,454] Trial 4 finished with value: 0.8001790199424234 and parameters: {'n_estimators': 800, 'learning_rate': 0.015955492733610785, 'max_depth': 8, 'subsample': 0.6765809022670964, 'colsample_bytree': 0.659549978798813, 'gamma': 0.13239151056312382}. Best is trial 0 with value: 0.8026503196664804.
<ipython-input-134-1caae69baf53>:9: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.2),
<ipython-input-134-1caae69baf53>:11: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:12: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:13: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'gamma': trial.suggest_uniform('gamma', 0, 1),

Fold 1/5

Fold 2/5

Fold 3/5

Fold 4/5

Fold 5/5

[I 2025-04-28 15:11:43,795] Trial 5 finished with value: 0.8028970630018438 and parameters: {'n_estimators': 1900, 'learning_rate': 0.060193232369786506, 'max_depth': 4, 'subsample': 0.8240311035580017, 'colsample_bytree': 0.9537990562842271, 'gamma': 0.8692640691813153}. Best is trial 5 with value: 0.8028970630018438.
<ipython-input-134-1caae69baf53>:9: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.2),
<ipython-input-134-1caae69baf53>:11: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:12: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:13: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'gamma': trial.suggest_uniform('gamma', 0, 1),

Fold 1/5

Fold 2/5

Fold 3/5

Fold 4/5

Fold 5/5

[I 2025-04-28 15:11:50,201] Trial 6 finished with value: 0.8022786206065122 and parameters: {'n_estimators': 1400, 'learning_rate': 0.059343334323569155, 'max_depth': 5, 'subsample': 0.7232561402386507, 'colsample_bytree': 0.6738998139753802, 'gamma': 0.10326282351407812}. Best is trial 5 with value: 0.8028970630018438.
<ipython-input-134-1caae69baf53>:9: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.2),
<ipython-input-134-1caae69baf53>:11: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:12: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:13: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'gamma': trial.suggest_uniform('gamma', 0, 1),

Fold 1/5

Fold 2/5

Fold 3/5

Fold 4/5

Fold 5/5

[I 2025-04-28 15:11:52,137] Trial 7 finished with value: 0.8000998936462349 and parameters: {'n_estimators': 1000, 'learning_rate': 0.14932702813706336, 'max_depth': 4, 'subsample': 0.8185729104808543, 'colsample_bytree': 0.773396144576706, 'gamma': 0.2975233310194041}. Best is trial 5 with value: 0.8028970630018438.
<ipython-input-134-1caae69baf53>:9: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.2),
<ipython-input-134-1caae69baf53>:11: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:12: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:13: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'gamma': trial.suggest_uniform('gamma', 0, 1),

Fold 1/5

Fold 2/5

Fold 3/5

Fold 4/5

Fold 5/5

[I 2025-04-28 15:11:57,259] Trial 8 finished with value: 0.7989261563587051 and parameters: {'n_estimators': 800, 'learning_rate': 0.040950182613759656, 'max_depth': 11, 'subsample': 0.8328845113134746, 'colsample_bytree': 0.7501691458621381, 'gamma': 0.05345380211610318}. Best is trial 5 with value: 0.8028970630018438.
<ipython-input-134-1caae69baf53>:9: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.2),
<ipython-input-134-1caae69baf53>:11: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:12: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:13: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'gamma': trial.suggest_uniform('gamma', 0, 1),

Fold 1/5

Fold 2/5

Fold 3/5

Fold 4/5

Fold 5/5

[I 2025-04-28 15:12:18,594] Trial 9 finished with value: 0.794114836921451 and parameters: {'n_estimators': 800, 'learning_rate': 0.011888492728460766, 'max_depth': 15, 'subsample': 0.9653956716255632, 'colsample_bytree': 0.8653203248888228, 'gamma': 0.4766471391182182}. Best is trial 5 with value: 0.8028970630018438.
<ipython-input-134-1caae69baf53>:9: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.2),
<ipython-input-134-1caae69baf53>:11: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:12: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:13: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'gamma': trial.suggest_uniform('gamma', 0, 1),

Fold 1/5

Fold 2/5

Fold 3/5

Fold 4/5

Fold 5/5

[I 2025-04-28 15:12:20,916] Trial 10 finished with value: 0.7967247683151978 and parameters: {'n_estimators': 100, 'learning_rate': 0.025229682168344283, 'max_depth': 6, 'subsample': 0.8945685475673719, 'colsample_bytree': 0.993747806760841, 'gamma': 0.9980243226423569}. Best is trial 5 with value: 0.8028970630018438.
<ipython-input-134-1caae69baf53>:9: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.2),
<ipython-input-134-1caae69baf53>:11: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:12: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:13: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'gamma': trial.suggest_uniform('gamma', 0, 1),

Fold 1/5

Fold 2/5

Fold 3/5

Fold 4/5

Fold 5/5

[I 2025-04-28 15:12:23,810] Trial 11 finished with value: 0.7999482968740776 and parameters: {'n_estimators': 2000, 'learning_rate': 0.09210314938995211, 'max_depth': 3, 'subsample': 0.7408742665971549, 'colsample_bytree': 0.9962114742753195, 'gamma': 0.841170260716567}. Best is trial 5 with value: 0.8028970630018438.
<ipython-input-134-1caae69baf53>:9: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.2),
<ipython-input-134-1caae69baf53>:11: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:12: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:13: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'gamma': trial.suggest_uniform('gamma', 0, 1),

Fold 1/5

Fold 2/5

Fold 3/5

Fold 4/5

Fold 5/5

[I 2025-04-28 15:12:27,689] Trial 12 finished with value: 0.7996482703997188 and parameters: {'n_estimators': 1500, 'learning_rate': 0.09229568752521254, 'max_depth': 6, 'subsample': 0.8748723162441383, 'colsample_bytree': 0.7134889824551427, 'gamma': 0.7410663088023697}. Best is trial 5 with value: 0.8028970630018438.
<ipython-input-134-1caae69baf53>:9: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.2),
<ipython-input-134-1caae69baf53>:11: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:12: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:13: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'gamma': trial.suggest_uniform('gamma', 0, 1),

Fold 1/5

Fold 2/5

Fold 3/5

Fold 4/5

Fold 5/5

[I 2025-04-28 15:12:36,933] Trial 13 finished with value: 0.8011474318019765 and parameters: {'n_estimators': 1600, 'learning_rate': 0.029635660641439215, 'max_depth': 3, 'subsample': 0.7558141211153313, 'colsample_bytree': 0.9225138737217041, 'gamma': 0.7260481790155363}. Best is trial 5 with value: 0.8028970630018438.
<ipython-input-134-1caae69baf53>:9: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.2),
<ipython-input-134-1caae69baf53>:11: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:12: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:13: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'gamma': trial.suggest_uniform('gamma', 0, 1),

Fold 1/5

Fold 2/5

Fold 3/5

Fold 4/5

Fold 5/5

[I 2025-04-28 15:12:41,777] Trial 14 finished with value: 0.7996517021491327 and parameters: {'n_estimators': 400, 'learning_rate': 0.06104362791736048, 'max_depth': 7, 'subsample': 0.8679944148907129, 'colsample_bytree': 0.6331115284307076, 'gamma': 0.935271579483848}. Best is trial 5 with value: 0.8028970630018438.
<ipython-input-134-1caae69baf53>:9: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.2),
<ipython-input-134-1caae69baf53>:11: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:12: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:13: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'gamma': trial.suggest_uniform('gamma', 0, 1),

Fold 1/5

Fold 2/5

Fold 3/5

Fold 4/5

Fold 5/5

[I 2025-04-28 15:12:44,621] Trial 15 finished with value: 0.7999215304730904 and parameters: {'n_estimators': 1800, 'learning_rate': 0.19626927125382396, 'max_depth': 5, 'subsample': 0.7696534797365272, 'colsample_bytree': 0.8158768470385819, 'gamma': 0.672321244196743}. Best is trial 5 with value: 0.8028970630018438.
<ipython-input-134-1caae69baf53>:9: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.2),
<ipython-input-134-1caae69baf53>:11: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:12: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:13: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'gamma': trial.suggest_uniform('gamma', 0, 1),

Fold 1/5

Fold 2/5

Fold 3/5

Fold 4/5

Fold 5/5

[I 2025-04-28 15:12:46,891] Trial 16 finished with value: 0.795269010686827 and parameters: {'n_estimators': 1200, 'learning_rate': 0.12244594950937102, 'max_depth': 11, 'subsample': 0.9198459180402804, 'colsample_bytree': 0.6009045604727684, 'gamma': 0.8557954682342972}. Best is trial 5 with value: 0.8028970630018438.
<ipython-input-134-1caae69baf53>:9: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.2),
<ipython-input-134-1caae69baf53>:11: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:12: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:13: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'gamma': trial.suggest_uniform('gamma', 0, 1),

Fold 1/5

Fold 2/5

Fold 3/5

Fold 4/5

Fold 5/5

[I 2025-04-28 15:12:50,519] Trial 17 finished with value: 0.7991906561400495 and parameters: {'n_estimators': 1100, 'learning_rate': 0.07279872407634737, 'max_depth': 3, 'subsample': 0.6182163948362391, 'colsample_bytree': 0.941162719565981, 'gamma': 0.6180023446612515}. Best is trial 5 with value: 0.8028970630018438.
<ipython-input-134-1caae69baf53>:9: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.2),
<ipython-input-134-1caae69baf53>:11: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:12: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:13: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'gamma': trial.suggest_uniform('gamma', 0, 1),

Fold 1/5

Fold 2/5

Fold 3/5

Fold 4/5

Fold 5/5

[I 2025-04-28 15:12:58,352] Trial 18 finished with value: 0.7996627672233496 and parameters: {'n_estimators': 1700, 'learning_rate': 0.0340519028517126, 'max_depth': 7, 'subsample': 0.8276376758808114, 'colsample_bytree': 0.8567594423607104, 'gamma': 0.8154613419562551}. Best is trial 5 with value: 0.8028970630018438.
<ipython-input-134-1caae69baf53>:9: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.2),
<ipython-input-134-1caae69baf53>:11: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:12: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:13: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'gamma': trial.suggest_uniform('gamma', 0, 1),

Fold 1/5

Fold 2/5

Fold 3/5

Fold 4/5

Fold 5/5

[I 2025-04-28 15:13:02,495] Trial 19 finished with value: 0.7995294500400307 and parameters: {'n_estimators': 300, 'learning_rate': 0.020161044069471175, 'max_depth': 5, 'subsample': 0.7039173906927276, 'colsample_bytree': 0.7120064306729157, 'gamma': 0.5766990094908366}. Best is trial 5 with value: 0.8028970630018438.
<ipython-input-134-1caae69baf53>:9: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.2),
<ipython-input-134-1caae69baf53>:11: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:12: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:13: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'gamma': trial.suggest_uniform('gamma', 0, 1),

Fold 1/5

Fold 2/5

Fold 3/5

Fold 4/5

Fold 5/5

[I 2025-04-28 15:13:04,854] Trial 20 finished with value: 0.7976568830844769 and parameters: {'n_estimators': 1800, 'learning_rate': 0.10946434742176651, 'max_depth': 10, 'subsample': 0.7808879243674276, 'colsample_bytree': 0.713923610287236, 'gamma': 0.8997906907609242}. Best is trial 5 with value: 0.8028970630018438.
<ipython-input-134-1caae69baf53>:9: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.2),
<ipython-input-134-1caae69baf53>:11: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:12: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:13: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'gamma': trial.suggest_uniform('gamma', 0, 1),

Fold 1/5

Fold 2/5

Fold 3/5

Fold 4/5

Fold 5/5

[I 2025-04-28 15:13:07,852] Trial 21 finished with value: 0.8035046782662267 and parameters: {'n_estimators': 1300, 'learning_rate': 0.061046542355491236, 'max_depth': 5, 'subsample': 0.7023737239196696, 'colsample_bytree': 0.6680983274004626, 'gamma': 0.33651556863388987}. Best is trial 21 with value: 0.8035046782662267.
<ipython-input-134-1caae69baf53>:9: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.2),
<ipython-input-134-1caae69baf53>:11: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:12: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:13: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'gamma': trial.suggest_uniform('gamma', 0, 1),

Fold 1/5

Fold 2/5

Fold 3/5

Fold 4/5

Fold 5/5

[I 2025-04-28 15:13:14,330] Trial 22 finished with value: 0.8013954979211046 and parameters: {'n_estimators': 1100, 'learning_rate': 0.056065785537030996, 'max_depth': 4, 'subsample': 0.8510877763118645, 'colsample_bytree': 0.6644529845494183, 'gamma': 0.36495490893979354}. Best is trial 21 with value: 0.8035046782662267.
<ipython-input-134-1caae69baf53>:9: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.2),
<ipython-input-134-1caae69baf53>:11: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:12: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:13: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'gamma': trial.suggest_uniform('gamma', 0, 1),

Fold 1/5

Fold 2/5

Fold 3/5

Fold 4/5

Fold 5/5

[I 2025-04-28 15:13:19,128] Trial 23 finished with value: 0.79999776450314 and parameters: {'n_estimators': 1400, 'learning_rate': 0.04298434573738981, 'max_depth': 4, 'subsample': 0.6035658993217486, 'colsample_bytree': 0.7332244517234712, 'gamma': 0.2538595969524468}. Best is trial 21 with value: 0.8035046782662267.
<ipython-input-134-1caae69baf53>:9: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.2),
<ipython-input-134-1caae69baf53>:11: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:12: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:13: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'gamma': trial.suggest_uniform('gamma', 0, 1),

Fold 1/5

Fold 2/5

Fold 3/5

Fold 4/5

Fold 5/5

[I 2025-04-28 15:13:23,067] Trial 24 finished with value: 0.7996356080823425 and parameters: {'n_estimators': 1300, 'learning_rate': 0.0731998708938194, 'max_depth': 6, 'subsample': 0.7990179959656405, 'colsample_bytree': 0.7782609955125834, 'gamma': 0.7609676640266083}. Best is trial 21 with value: 0.8035046782662267.
<ipython-input-134-1caae69baf53>:9: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.2),
<ipython-input-134-1caae69baf53>:11: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:12: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:13: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'gamma': trial.suggest_uniform('gamma', 0, 1),

Fold 1/5

Fold 2/5

Fold 3/5

Fold 4/5

Fold 5/5

[I 2025-04-28 15:13:26,648] Trial 25 finished with value: 0.7991184838244367 and parameters: {'n_estimators': 900, 'learning_rate': 0.13405243316364862, 'max_depth': 7, 'subsample': 0.6926636285370639, 'colsample_bytree': 0.6893779272056015, 'gamma': 0.634126446843154}. Best is trial 21 with value: 0.8035046782662267.
<ipython-input-134-1caae69baf53>:9: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.2),
<ipython-input-134-1caae69baf53>:11: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:12: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:13: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'gamma': trial.suggest_uniform('gamma', 0, 1),

Fold 1/5

Fold 2/5

Fold 3/5

Fold 4/5

Fold 5/5

[I 2025-04-28 15:13:30,009] Trial 26 finished with value: 0.7986569174874056 and parameters: {'n_estimators': 1200, 'learning_rate': 0.07203477764569652, 'max_depth': 4, 'subsample': 0.9950526669927919, 'colsample_bytree': 0.6234321891173727, 'gamma': 0.3768161324329118}. Best is trial 21 with value: 0.8035046782662267.
<ipython-input-134-1caae69baf53>:9: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.2),
<ipython-input-134-1caae69baf53>:11: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:12: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:13: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'gamma': trial.suggest_uniform('gamma', 0, 1),

Fold 1/5

Fold 2/5

Fold 3/5

Fold 4/5

Fold 5/5

[I 2025-04-28 15:13:32,215] Trial 27 finished with value: 0.8004417967857579 and parameters: {'n_estimators': 1600, 'learning_rate': 0.09867688178982892, 'max_depth': 5, 'subsample': 0.9072796539926675, 'colsample_bytree': 0.7994429651942395, 'gamma': 0.18437002944407532}. Best is trial 21 with value: 0.8035046782662267.
<ipython-input-134-1caae69baf53>:9: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.2),
<ipython-input-134-1caae69baf53>:11: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:12: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:13: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'gamma': trial.suggest_uniform('gamma', 0, 1),

Fold 1/5

Fold 2/5

Fold 3/5

Fold 4/5

Fold 5/5

[I 2025-04-28 15:13:40,400] Trial 28 finished with value: 0.8001854664250345 and parameters: {'n_estimators': 1800, 'learning_rate': 0.04985451936290624, 'max_depth': 3, 'subsample': 0.6480895982879366, 'colsample_bytree': 0.6390493300400607, 'gamma': 0.9634533708346793}. Best is trial 21 with value: 0.8035046782662267.
<ipython-input-134-1caae69baf53>:9: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.2),
<ipython-input-134-1caae69baf53>:11: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:12: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:13: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'gamma': trial.suggest_uniform('gamma', 0, 1),

Fold 1/5

Fold 2/5

Fold 3/5

Fold 4/5

Fold 5/5

[I 2025-04-28 15:13:44,646] Trial 29 finished with value: 0.8002328928174643 and parameters: {'n_estimators': 600, 'learning_rate': 0.036796987347001923, 'max_depth': 6, 'subsample': 0.7326067150920543, 'colsample_bytree': 0.960356574925477, 'gamma': 0.519047992658545}. Best is trial 21 with value: 0.8035046782662267.
<ipython-input-134-1caae69baf53>:9: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.2),
<ipython-input-134-1caae69baf53>:11: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:12: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:13: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'gamma': trial.suggest_uniform('gamma', 0, 1),

Fold 1/5

Fold 2/5

Fold 3/5

Fold 4/5

Fold 5/5

[I 2025-04-28 15:13:46,520] Trial 30 finished with value: 0.7979884183905688 and parameters: {'n_estimators': 1000, 'learning_rate': 0.16759428334645773, 'max_depth': 8, 'subsample': 0.7822982870063616, 'colsample_bytree': 0.8402971945185922, 'gamma': 0.7929499239839917}. Best is trial 21 with value: 0.8035046782662267.
<ipython-input-134-1caae69baf53>:9: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.2),
<ipython-input-134-1caae69baf53>:11: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:12: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:13: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'gamma': trial.suggest_uniform('gamma', 0, 1),

Fold 1/5

Fold 2/5

Fold 3/5

Fold 4/5

Fold 5/5

[I 2025-04-28 15:13:50,607] Trial 31 finished with value: 0.8016525392141286 and parameters: {'n_estimators': 1300, 'learning_rate': 0.06254254090634442, 'max_depth': 5, 'subsample': 0.7163614982959229, 'colsample_bytree': 0.6806862807232098, 'gamma': 0.02269599671855782}. Best is trial 21 with value: 0.8035046782662267.
<ipython-input-134-1caae69baf53>:9: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.2),
<ipython-input-134-1caae69baf53>:11: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:12: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:13: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'gamma': trial.suggest_uniform('gamma', 0, 1),

Fold 1/5

Fold 2/5

Fold 3/5

Fold 4/5

Fold 5/5

[I 2025-04-28 15:13:56,438] Trial 32 finished with value: 0.8041658262994972 and parameters: {'n_estimators': 1400, 'learning_rate': 0.04931476093184571, 'max_depth': 4, 'subsample': 0.6578843387359619, 'colsample_bytree': 0.6902394255031622, 'gamma': 0.11174367093570015}. Best is trial 32 with value: 0.8041658262994972.
<ipython-input-134-1caae69baf53>:9: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.2),
<ipython-input-134-1caae69baf53>:11: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:12: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:13: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'gamma': trial.suggest_uniform('gamma', 0, 1),

Fold 1/5

Fold 2/5

Fold 3/5

Fold 4/5

Fold 5/5

[I 2025-04-28 15:14:00,195] Trial 33 finished with value: 0.8022491041424059 and parameters: {'n_estimators': 1500, 'learning_rate': 0.04842104942234919, 'max_depth': 4, 'subsample': 0.6478994992655842, 'colsample_bytree': 0.8902819921082832, 'gamma': 0.22053148866903238}. Best is trial 32 with value: 0.8041658262994972.
<ipython-input-134-1caae69baf53>:9: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.2),
<ipython-input-134-1caae69baf53>:11: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:12: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:13: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'gamma': trial.suggest_uniform('gamma', 0, 1),

Fold 1/5

Fold 2/5

Fold 3/5

Fold 4/5

Fold 5/5

[I 2025-04-28 15:14:11,557] Trial 34 finished with value: 0.7996859967190326 and parameters: {'n_estimators': 1200, 'learning_rate': 0.028335393643787246, 'max_depth': 3, 'subsample': 0.674437849274999, 'colsample_bytree': 0.7437925559324207, 'gamma': 0.31436163517797056}. Best is trial 32 with value: 0.8041658262994972.
<ipython-input-134-1caae69baf53>:9: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.2),
<ipython-input-134-1caae69baf53>:11: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:12: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:13: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'gamma': trial.suggest_uniform('gamma', 0, 1),

Fold 1/5

Fold 2/5

Fold 3/5

Fold 4/5

Fold 5/5

[I 2025-04-28 15:14:14,565] Trial 35 finished with value: 0.8003991875673429 and parameters: {'n_estimators': 1900, 'learning_rate': 0.07015607657291195, 'max_depth': 8, 'subsample': 0.6283509662185709, 'colsample_bytree': 0.6923373466491521, 'gamma': 0.17324215915282504}. Best is trial 32 with value: 0.8041658262994972.
<ipython-input-134-1caae69baf53>:9: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.2),
<ipython-input-134-1caae69baf53>:11: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:12: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:13: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'gamma': trial.suggest_uniform('gamma', 0, 1),

Fold 1/5

Fold 2/5

Fold 3/5

Fold 4/5

Fold 5/5

[I 2025-04-28 15:14:20,041] Trial 36 finished with value: 0.8014593576112571 and parameters: {'n_estimators': 600, 'learning_rate': 0.08125643212495458, 'max_depth': 4, 'subsample': 0.6745756812272261, 'colsample_bytree': 0.6573752948579693, 'gamma': 0.4748069259891522}. Best is trial 32 with value: 0.8041658262994972.
<ipython-input-134-1caae69baf53>:9: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.2),
<ipython-input-134-1caae69baf53>:11: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:12: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:13: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'gamma': trial.suggest_uniform('gamma', 0, 1),

Fold 1/5

Fold 2/5

Fold 3/5

Fold 4/5

Fold 5/5

[I 2025-04-28 15:14:23,056] Trial 37 finished with value: 0.7966273685534306 and parameters: {'n_estimators': 1500, 'learning_rate': 0.10795970713891478, 'max_depth': 9, 'subsample': 0.7961504399491514, 'colsample_bytree': 0.7920861631533312, 'gamma': 0.07994247110398989}. Best is trial 32 with value: 0.8041658262994972.
<ipython-input-134-1caae69baf53>:9: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.2),
<ipython-input-134-1caae69baf53>:11: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:12: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:13: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'gamma': trial.suggest_uniform('gamma', 0, 1),

Fold 1/5

Fold 2/5

Fold 3/5

Fold 4/5

Fold 5/5

[I 2025-04-28 15:14:27,568] Trial 38 finished with value: 0.7955780420162594 and parameters: {'n_estimators': 900, 'learning_rate': 0.052468390481009534, 'max_depth': 13, 'subsample': 0.8469489315510834, 'colsample_bytree': 0.727390326155297, 'gamma': 0.4195773397467683}. Best is trial 32 with value: 0.8041658262994972.
<ipython-input-134-1caae69baf53>:9: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.2),
<ipython-input-134-1caae69baf53>:11: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:12: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:13: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'gamma': trial.suggest_uniform('gamma', 0, 1),

Fold 1/5

Fold 2/5

Fold 3/5

Fold 4/5

Fold 5/5

[I 2025-04-28 15:14:34,728] Trial 39 finished with value: 0.8032841659191007 and parameters: {'n_estimators': 1300, 'learning_rate': 0.03811595600439704, 'max_depth': 5, 'subsample': 0.7639319066559922, 'colsample_bytree': 0.6507139778476376, 'gamma': 7.24308997199774e-05}. Best is trial 32 with value: 0.8041658262994972.
<ipython-input-134-1caae69baf53>:9: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.2),
<ipython-input-134-1caae69baf53>:11: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:12: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:13: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'gamma': trial.suggest_uniform('gamma', 0, 1),

Fold 1/5

Fold 2/5

Fold 3/5

Fold 4/5

Fold 5/5

[I 2025-04-28 15:14:38,846] Trial 40 finished with value: 0.8019309054082138 and parameters: {'n_estimators': 1300, 'learning_rate': 0.04008320313779354, 'max_depth': 6, 'subsample': 0.7514665993430096, 'colsample_bytree': 0.6479962181839656, 'gamma': 0.008799032385766447}. Best is trial 32 with value: 0.8041658262994972.
<ipython-input-134-1caae69baf53>:9: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.2),
<ipython-input-134-1caae69baf53>:11: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:12: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:13: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'gamma': trial.suggest_uniform('gamma', 0, 1),

Fold 1/5

Fold 2/5

Fold 3/5

Fold 4/5

Fold 5/5

[I 2025-04-28 15:14:49,114] Trial 41 finished with value: 0.8012117279418091 and parameters: {'n_estimators': 1600, 'learning_rate': 0.022153114476275316, 'max_depth': 5, 'subsample': 0.8150746196194414, 'colsample_bytree': 0.6077682764393718, 'gamma': 0.1362265264165545}. Best is trial 32 with value: 0.8041658262994972.
<ipython-input-134-1caae69baf53>:9: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.2),
<ipython-input-134-1caae69baf53>:11: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:12: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:13: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'gamma': trial.suggest_uniform('gamma', 0, 1),

Fold 1/5

Fold 2/5

Fold 3/5

Fold 4/5

Fold 5/5

[I 2025-04-28 15:14:54,666] Trial 42 finished with value: 0.8020719425574596 and parameters: {'n_estimators': 1000, 'learning_rate': 0.033008623730326044, 'max_depth': 4, 'subsample': 0.6968093473215035, 'colsample_bytree': 0.6978973455178946, 'gamma': 0.08582355613010534}. Best is trial 32 with value: 0.8041658262994972.
<ipython-input-134-1caae69baf53>:9: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.2),
<ipython-input-134-1caae69baf53>:11: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:12: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:13: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'gamma': trial.suggest_uniform('gamma', 0, 1),

Fold 1/5

Fold 2/5

Fold 3/5

Fold 4/5

Fold 5/5

[I 2025-04-28 15:14:58,709] Trial 43 finished with value: 0.8023546689272514 and parameters: {'n_estimators': 1400, 'learning_rate': 0.04376442119141316, 'max_depth': 5, 'subsample': 0.7588817557566769, 'colsample_bytree': 0.6725749384280306, 'gamma': 0.151902135248604}. Best is trial 32 with value: 0.8041658262994972.
<ipython-input-134-1caae69baf53>:9: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.2),
<ipython-input-134-1caae69baf53>:11: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:12: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:13: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'gamma': trial.suggest_uniform('gamma', 0, 1),

Fold 1/5

Fold 2/5

Fold 3/5

Fold 4/5

Fold 5/5

[I 2025-04-28 15:15:05,655] Trial 44 finished with value: 0.8012009671066403 and parameters: {'n_estimators': 1200, 'learning_rate': 0.05985955928539708, 'max_depth': 3, 'subsample': 0.718442896707636, 'colsample_bytree': 0.7723236338747702, 'gamma': 0.04720622602105773}. Best is trial 32 with value: 0.8041658262994972.
<ipython-input-134-1caae69baf53>:9: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.2),
<ipython-input-134-1caae69baf53>:11: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:12: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:13: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'gamma': trial.suggest_uniform('gamma', 0, 1),

Fold 1/5

Fold 2/5

Fold 3/5

Fold 4/5

Fold 5/5

[I 2025-04-28 15:15:16,690] Trial 45 finished with value: 0.799555268533638 and parameters: {'n_estimators': 2000, 'learning_rate': 0.01604889607622522, 'max_depth': 7, 'subsample': 0.8386312724288698, 'colsample_bytree': 0.7534840059908108, 'gamma': 0.22207174823626497}. Best is trial 32 with value: 0.8041658262994972.
<ipython-input-134-1caae69baf53>:9: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.2),
<ipython-input-134-1caae69baf53>:11: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:12: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:13: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'gamma': trial.suggest_uniform('gamma', 0, 1),

Fold 1/5

Fold 2/5

Fold 3/5

Fold 4/5

Fold 5/5

[I 2025-04-28 15:15:19,771] Trial 46 finished with value: 0.800816200913582 and parameters: {'n_estimators': 700, 'learning_rate': 0.07917452356898595, 'max_depth': 4, 'subsample': 0.8666520404229724, 'colsample_bytree': 0.6218986473835254, 'gamma': 0.8825152315308368}. Best is trial 32 with value: 0.8041658262994972.
<ipython-input-134-1caae69baf53>:9: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.2),
<ipython-input-134-1caae69baf53>:11: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:12: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:13: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'gamma': trial.suggest_uniform('gamma', 0, 1),

Fold 1/5

Fold 2/5

Fold 3/5

Fold 4/5

Fold 5/5

[I 2025-04-28 15:15:24,097] Trial 47 finished with value: 0.8013492721316535 and parameters: {'n_estimators': 900, 'learning_rate': 0.03835382334579312, 'max_depth': 6, 'subsample': 0.8046053023113461, 'colsample_bytree': 0.6546815512909904, 'gamma': 0.7080096713635295}. Best is trial 32 with value: 0.8041658262994972.
<ipython-input-134-1caae69baf53>:9: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.2),
<ipython-input-134-1caae69baf53>:11: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:12: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:13: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'gamma': trial.suggest_uniform('gamma', 0, 1),

Fold 1/5

Fold 2/5

Fold 3/5

Fold 4/5

Fold 5/5

[I 2025-04-28 15:15:34,277] Trial 48 finished with value: 0.7960539804680384 and parameters: {'n_estimators': 1700, 'learning_rate': 0.02932417122686025, 'max_depth': 14, 'subsample': 0.7441052075115685, 'colsample_bytree': 0.7078184958575424, 'gamma': 0.11829891647111883}. Best is trial 32 with value: 0.8041658262994972.
<ipython-input-134-1caae69baf53>:9: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.2),
<ipython-input-134-1caae69baf53>:11: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:12: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:13: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'gamma': trial.suggest_uniform('gamma', 0, 1),

Fold 1/5

Fold 2/5

Fold 3/5

Fold 4/5

Fold 5/5

[I 2025-04-28 15:15:47,858] Trial 49 finished with value: 0.7958730629779 and parameters: {'n_estimators': 1100, 'learning_rate': 0.010271255255640288, 'max_depth': 3, 'subsample': 0.886333173833657, 'colsample_bytree': 0.8941870245462757, 'gamma': 0.5660714624594739}. Best is trial 32 with value: 0.8041658262994972.
<ipython-input-134-1caae69baf53>:9: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.2),
<ipython-input-134-1caae69baf53>:11: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:12: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:13: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'gamma': trial.suggest_uniform('gamma', 0, 1),

Fold 1/5

Fold 2/5

Fold 3/5

Fold 4/5

Fold 5/5

[I 2025-04-28 15:15:51,343] Trial 50 finished with value: 0.801347333124629 and parameters: {'n_estimators': 1300, 'learning_rate': 0.06324638254174982, 'max_depth': 5, 'subsample': 0.9363990741125169, 'colsample_bytree': 0.6726053253662438, 'gamma': 0.32481923357825404}. Best is trial 32 with value: 0.8041658262994972.
<ipython-input-134-1caae69baf53>:9: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.2),
<ipython-input-134-1caae69baf53>:11: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:12: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:13: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'gamma': trial.suggest_uniform('gamma', 0, 1),

Fold 1/5

Fold 2/5

Fold 3/5

Fold 4/5

Fold 5/5

[I 2025-04-28 15:15:58,259] Trial 51 finished with value: 0.8018925713229452 and parameters: {'n_estimators': 1500, 'learning_rate': 0.0446213734277812, 'max_depth': 5, 'subsample': 0.7669692328575579, 'colsample_bytree': 0.6751692873044768, 'gamma': 0.14070683641312873}. Best is trial 32 with value: 0.8041658262994972.
<ipython-input-134-1caae69baf53>:9: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.2),
<ipython-input-134-1caae69baf53>:11: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:12: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:13: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'gamma': trial.suggest_uniform('gamma', 0, 1),

Fold 1/5

Fold 2/5

Fold 3/5

Fold 4/5

Fold 5/5

[I 2025-04-28 15:16:02,078] Trial 52 finished with value: 0.7996559557336872 and parameters: {'n_estimators': 1400, 'learning_rate': 0.04627398952706033, 'max_depth': 6, 'subsample': 0.76958194163186, 'colsample_bytree': 0.6376700793641884, 'gamma': 0.0033045028622591954}. Best is trial 32 with value: 0.8041658262994972.
<ipython-input-134-1caae69baf53>:9: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.2),
<ipython-input-134-1caae69baf53>:11: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:12: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:13: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'gamma': trial.suggest_uniform('gamma', 0, 1),

Fold 1/5

Fold 2/5

Fold 3/5

Fold 4/5

Fold 5/5

[I 2025-04-28 15:16:05,511] Trial 53 finished with value: 0.8019033582188604 and parameters: {'n_estimators': 1400, 'learning_rate': 0.053494121929347285, 'max_depth': 5, 'subsample': 0.8176233922341571, 'colsample_bytree': 0.697483185944144, 'gamma': 0.06745210214109515}. Best is trial 32 with value: 0.8041658262994972.
<ipython-input-134-1caae69baf53>:9: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.2),
<ipython-input-134-1caae69baf53>:11: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:12: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:13: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'gamma': trial.suggest_uniform('gamma', 0, 1),

Fold 1/5

Fold 2/5

Fold 3/5

Fold 4/5

Fold 5/5

[I 2025-04-28 15:16:13,905] Trial 54 finished with value: 0.8018532617406248 and parameters: {'n_estimators': 1700, 'learning_rate': 0.033848026541617865, 'max_depth': 4, 'subsample': 0.7870498317242904, 'colsample_bytree': 0.7269714274756575, 'gamma': 0.2553511316745085}. Best is trial 32 with value: 0.8041658262994972.
<ipython-input-134-1caae69baf53>:9: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.2),
<ipython-input-134-1caae69baf53>:11: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:12: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:13: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'gamma': trial.suggest_uniform('gamma', 0, 1),

Fold 1/5

Fold 2/5

Fold 3/5

Fold 4/5

Fold 5/5

[I 2025-04-28 15:16:17,300] Trial 55 finished with value: 0.8009123445825284 and parameters: {'n_estimators': 1200, 'learning_rate': 0.08854343984456933, 'max_depth': 3, 'subsample': 0.6672542488566355, 'colsample_bytree': 0.8188849800134347, 'gamma': 0.18944668080682495}. Best is trial 32 with value: 0.8041658262994972.
<ipython-input-134-1caae69baf53>:9: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.2),
<ipython-input-134-1caae69baf53>:11: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:12: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:13: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'gamma': trial.suggest_uniform('gamma', 0, 1),

Fold 1/5

Fold 2/5

Fold 3/5

Fold 4/5

Fold 5/5

[I 2025-04-28 15:16:27,977] Trial 56 finished with value: 0.802896082855732 and parameters: {'n_estimators': 1900, 'learning_rate': 0.02605895027188967, 'max_depth': 4, 'subsample': 0.72711630191542, 'colsample_bytree': 0.6196647825779285, 'gamma': 0.9356521970654714}. Best is trial 32 with value: 0.8041658262994972.
<ipython-input-134-1caae69baf53>:9: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.2),
<ipython-input-134-1caae69baf53>:11: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:12: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:13: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'gamma': trial.suggest_uniform('gamma', 0, 1),

Fold 1/5

Fold 2/5

Fold 3/5

Fold 4/5

Fold 5/5

[I 2025-04-28 15:16:38,468] Trial 57 finished with value: 0.8020418862897003 and parameters: {'n_estimators': 1900, 'learning_rate': 0.018877088054756096, 'max_depth': 4, 'subsample': 0.7300865441898401, 'colsample_bytree': 0.618686146857633, 'gamma': 0.9953718365610886}. Best is trial 32 with value: 0.8041658262994972.
<ipython-input-134-1caae69baf53>:9: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.2),
<ipython-input-134-1caae69baf53>:11: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:12: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:13: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'gamma': trial.suggest_uniform('gamma', 0, 1),

Fold 1/5

Fold 2/5

Fold 3/5

Fold 4/5

Fold 5/5

[I 2025-04-28 15:16:47,075] Trial 58 finished with value: 0.799743493751254 and parameters: {'n_estimators': 1900, 'learning_rate': 0.022828948655045575, 'max_depth': 3, 'subsample': 0.6904680229165763, 'colsample_bytree': 0.96803138231157, 'gamma': 0.9075266440310663}. Best is trial 32 with value: 0.8041658262994972.
<ipython-input-134-1caae69baf53>:9: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.2),
<ipython-input-134-1caae69baf53>:11: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:12: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:13: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'gamma': trial.suggest_uniform('gamma', 0, 1),

Fold 1/5

Fold 2/5

Fold 3/5

Fold 4/5

Fold 5/5

[I 2025-04-28 15:16:55,892] Trial 59 finished with value: 0.8021622486412425 and parameters: {'n_estimators': 1600, 'learning_rate': 0.026553970334876224, 'max_depth': 4, 'subsample': 0.6325463495417832, 'colsample_bytree': 0.6463850407023575, 'gamma': 0.8361482947259908}. Best is trial 32 with value: 0.8041658262994972.
<ipython-input-134-1caae69baf53>:9: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.2),
<ipython-input-134-1caae69baf53>:11: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:12: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:13: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'gamma': trial.suggest_uniform('gamma', 0, 1),

Fold 1/5

Fold 2/5

Fold 3/5

Fold 4/5

Fold 5/5

[I 2025-04-28 15:16:58,990] Trial 60 finished with value: 0.799693034032394 and parameters: {'n_estimators': 2000, 'learning_rate': 0.06607868971781702, 'max_depth': 7, 'subsample': 0.7126790855473534, 'colsample_bytree': 0.9188624164896908, 'gamma': 0.7974628000865983}. Best is trial 32 with value: 0.8041658262994972.
<ipython-input-134-1caae69baf53>:9: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.2),
<ipython-input-134-1caae69baf53>:11: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:12: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:13: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'gamma': trial.suggest_uniform('gamma', 0, 1),

Fold 1/5

Fold 2/5

Fold 3/5

Fold 4/5

Fold 5/5

[I 2025-04-28 15:17:07,087] Trial 61 finished with value: 0.8033925521497176 and parameters: {'n_estimators': 1400, 'learning_rate': 0.03155166164666961, 'max_depth': 5, 'subsample': 0.7537042695018573, 'colsample_bytree': 0.6653186611569866, 'gamma': 0.8605961197407072}. Best is trial 32 with value: 0.8041658262994972.
<ipython-input-134-1caae69baf53>:9: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.2),
<ipython-input-134-1caae69baf53>:11: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:12: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:13: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'gamma': trial.suggest_uniform('gamma', 0, 1),

Fold 1/5

Fold 2/5

Fold 3/5

Fold 4/5

Fold 5/5

[I 2025-04-28 15:17:12,398] Trial 62 finished with value: 0.8014294506271055 and parameters: {'n_estimators': 1300, 'learning_rate': 0.03155031731962891, 'max_depth': 5, 'subsample': 0.6568936227103293, 'colsample_bytree': 0.6613689514108064, 'gamma': 0.939470887963309}. Best is trial 32 with value: 0.8041658262994972.
<ipython-input-134-1caae69baf53>:9: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.2),
<ipython-input-134-1caae69baf53>:11: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:12: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:13: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'gamma': trial.suggest_uniform('gamma', 0, 1),

Fold 1/5

Fold 2/5

Fold 3/5

Fold 4/5

Fold 5/5

[I 2025-04-28 15:17:21,927] Trial 63 finished with value: 0.8016894717064152 and parameters: {'n_estimators': 1100, 'learning_rate': 0.025689314101501413, 'max_depth': 4, 'subsample': 0.744466499617934, 'colsample_bytree': 0.6298597022844025, 'gamma': 0.890130145937358}. Best is trial 32 with value: 0.8041658262994972.
<ipython-input-134-1caae69baf53>:9: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.2),
<ipython-input-134-1caae69baf53>:11: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:12: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:13: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'gamma': trial.suggest_uniform('gamma', 0, 1),

Fold 1/5

Fold 2/5

Fold 3/5

Fold 4/5

Fold 5/5

[I 2025-04-28 15:17:26,154] Trial 64 finished with value: 0.8024573016822554 and parameters: {'n_estimators': 1800, 'learning_rate': 0.038445069103377714, 'max_depth': 5, 'subsample': 0.7354628223335034, 'colsample_bytree': 0.6084503666764788, 'gamma': 0.8638915429488292}. Best is trial 32 with value: 0.8041658262994972.
<ipython-input-134-1caae69baf53>:9: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.2),
<ipython-input-134-1caae69baf53>:11: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:12: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:13: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'gamma': trial.suggest_uniform('gamma', 0, 1),

Fold 1/5

Fold 2/5

Fold 3/5

Fold 4/5

Fold 5/5

[I 2025-04-28 15:17:28,264] Trial 65 finished with value: 0.7994834282310834 and parameters: {'n_estimators': 1500, 'learning_rate': 0.17252867666983196, 'max_depth': 3, 'subsample': 0.7050872432161913, 'colsample_bytree': 0.6862435768860325, 'gamma': 0.7579751623866662}. Best is trial 32 with value: 0.8041658262994972.
<ipython-input-134-1caae69baf53>:9: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.2),
<ipython-input-134-1caae69baf53>:11: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:12: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:13: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'gamma': trial.suggest_uniform('gamma', 0, 1),

Fold 1/5

Fold 2/5

Fold 3/5

Fold 4/5

Fold 5/5

[I 2025-04-28 15:17:35,635] Trial 66 finished with value: 0.8003083476401048 and parameters: {'n_estimators': 1000, 'learning_rate': 0.03553073043360768, 'max_depth': 6, 'subsample': 0.7885913033267548, 'colsample_bytree': 0.7081763387445217, 'gamma': 0.9337539328072161}. Best is trial 32 with value: 0.8041658262994972.
<ipython-input-134-1caae69baf53>:9: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.2),
<ipython-input-134-1caae69baf53>:11: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:12: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:13: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'gamma': trial.suggest_uniform('gamma', 0, 1),

Fold 1/5

Fold 2/5

Fold 3/5

Fold 4/5

Fold 5/5

[I 2025-04-28 15:17:37,659] Trial 67 finished with value: 0.7999916978169586 and parameters: {'n_estimators': 1400, 'learning_rate': 0.14146862310674743, 'max_depth': 4, 'subsample': 0.8256932659738165, 'colsample_bytree': 0.6424440929076113, 'gamma': 0.6428229979790341}. Best is trial 32 with value: 0.8041658262994972.
<ipython-input-134-1caae69baf53>:9: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.2),
<ipython-input-134-1caae69baf53>:11: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:12: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:13: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'gamma': trial.suggest_uniform('gamma', 0, 1),

Fold 1/5

Fold 2/5

Fold 3/5

Fold 4/5

Fold 5/5

[I 2025-04-28 15:17:45,877] Trial 68 finished with value: 0.7983474095658356 and parameters: {'n_estimators': 1700, 'learning_rate': 0.02316894891729773, 'max_depth': 12, 'subsample': 0.6850723161833783, 'colsample_bytree': 0.6624054238560949, 'gamma': 0.8282448516512607}. Best is trial 32 with value: 0.8041658262994972.
<ipython-input-134-1caae69baf53>:9: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.2),
<ipython-input-134-1caae69baf53>:11: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:12: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:13: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'gamma': trial.suggest_uniform('gamma', 0, 1),

Fold 1/5

Fold 2/5

Fold 3/5

Fold 4/5

Fold 5/5

[I 2025-04-28 15:17:51,358] Trial 69 finished with value: 0.8012076401936976 and parameters: {'n_estimators': 400, 'learning_rate': 0.055303451078760966, 'max_depth': 5, 'subsample': 0.8546728032920726, 'colsample_bytree': 0.7412761683035926, 'gamma': 0.6816925273283743}. Best is trial 32 with value: 0.8041658262994972.
<ipython-input-134-1caae69baf53>:9: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.2),
<ipython-input-134-1caae69baf53>:11: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:12: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:13: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'gamma': trial.suggest_uniform('gamma', 0, 1),

Fold 1/5

Fold 2/5

Fold 3/5

Fold 4/5

Fold 5/5

[I 2025-04-28 15:17:55,403] Trial 70 finished with value: 0.8006272405627624 and parameters: {'n_estimators': 1900, 'learning_rate': 0.0419723911116111, 'max_depth': 10, 'subsample': 0.7621682743607479, 'colsample_bytree': 0.8749762108451468, 'gamma': 0.9559573840869732}. Best is trial 32 with value: 0.8041658262994972.
<ipython-input-134-1caae69baf53>:9: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.2),
<ipython-input-134-1caae69baf53>:11: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:12: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:13: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'gamma': trial.suggest_uniform('gamma', 0, 1),

Fold 1/5

Fold 2/5

Fold 3/5

Fold 4/5

Fold 5/5

[I 2025-04-28 15:18:02,529] Trial 71 finished with value: 0.8029270678456684 and parameters: {'n_estimators': 1800, 'learning_rate': 0.038703863006813465, 'max_depth': 5, 'subsample': 0.7299852870326563, 'colsample_bytree': 0.601082079805565, 'gamma': 0.8580105970334452}. Best is trial 32 with value: 0.8041658262994972.
<ipython-input-134-1caae69baf53>:9: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.2),
<ipython-input-134-1caae69baf53>:11: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:12: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:13: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'gamma': trial.suggest_uniform('gamma', 0, 1),

Fold 1/5

Fold 2/5

Fold 3/5

Fold 4/5

Fold 5/5

[I 2025-04-28 15:18:06,331] Trial 72 finished with value: 0.7994120864430421 and parameters: {'n_estimators': 1800, 'learning_rate': 0.04876770310013153, 'max_depth': 4, 'subsample': 0.7265026975573758, 'colsample_bytree': 0.6052540471251004, 'gamma': 0.8597424997075387}. Best is trial 32 with value: 0.8041658262994972.
<ipython-input-134-1caae69baf53>:9: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.2),
<ipython-input-134-1caae69baf53>:11: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:12: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:13: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'gamma': trial.suggest_uniform('gamma', 0, 1),

Fold 1/5

Fold 2/5

Fold 3/5

Fold 4/5

Fold 5/5

[I 2025-04-28 15:18:11,719] Trial 73 finished with value: 0.8019190256162225 and parameters: {'n_estimators': 1200, 'learning_rate': 0.02735169215252835, 'max_depth': 6, 'subsample': 0.7104561583755424, 'colsample_bytree': 0.6174265103936848, 'gamma': 0.7878017396642708}. Best is trial 32 with value: 0.8041658262994972.
<ipython-input-134-1caae69baf53>:9: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.2),
<ipython-input-134-1caae69baf53>:11: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:12: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:13: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'gamma': trial.suggest_uniform('gamma', 0, 1),

Fold 1/5

Fold 2/5

Fold 3/5

Fold 4/5

Fold 5/5

[I 2025-04-28 15:18:19,801] Trial 74 finished with value: 0.8015753048005847 and parameters: {'n_estimators': 1700, 'learning_rate': 0.03137550101778195, 'max_depth': 5, 'subsample': 0.774905946495007, 'colsample_bytree': 0.6519227068326345, 'gamma': 0.9172317911823284}. Best is trial 32 with value: 0.8041658262994972.
<ipython-input-134-1caae69baf53>:9: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.2),
<ipython-input-134-1caae69baf53>:11: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:12: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:13: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'gamma': trial.suggest_uniform('gamma', 0, 1),

Fold 1/5

Fold 2/5

Fold 3/5

Fold 4/5

Fold 5/5

[I 2025-04-28 15:18:24,771] Trial 75 finished with value: 0.8034799564610136 and parameters: {'n_estimators': 2000, 'learning_rate': 0.03979648262309452, 'max_depth': 4, 'subsample': 0.7516179963181187, 'colsample_bytree': 0.6310635220751031, 'gamma': 0.03652701311580644}. Best is trial 32 with value: 0.8041658262994972.
<ipython-input-134-1caae69baf53>:9: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.2),
<ipython-input-134-1caae69baf53>:11: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:12: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:13: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'gamma': trial.suggest_uniform('gamma', 0, 1),

Fold 1/5

Fold 2/5

Fold 3/5

Fold 4/5

Fold 5/5

[I 2025-04-28 15:18:32,389] Trial 76 finished with value: 0.7982059285468778 and parameters: {'n_estimators': 1900, 'learning_rate': 0.0361918125308575, 'max_depth': 8, 'subsample': 0.748825003379258, 'colsample_bytree': 0.63085711615809, 'gamma': 0.05057150443169112}. Best is trial 32 with value: 0.8041658262994972.
<ipython-input-134-1caae69baf53>:9: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.2),
<ipython-input-134-1caae69baf53>:11: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:12: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:13: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'gamma': trial.suggest_uniform('gamma', 0, 1),

Fold 1/5

Fold 2/5

Fold 3/5

Fold 4/5

Fold 5/5

[I 2025-04-28 15:18:35,906] Trial 77 finished with value: 0.8021724416966766 and parameters: {'n_estimators': 2000, 'learning_rate': 0.05091936337184029, 'max_depth': 6, 'subsample': 0.7232627372148611, 'colsample_bytree': 0.6299935466264528, 'gamma': 0.0929657264086916}. Best is trial 32 with value: 0.8041658262994972.
<ipython-input-134-1caae69baf53>:9: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.2),
<ipython-input-134-1caae69baf53>:11: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:12: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:13: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'gamma': trial.suggest_uniform('gamma', 0, 1),

Fold 1/5

Fold 2/5

Fold 3/5

Fold 4/5

Fold 5/5

[I 2025-04-28 15:18:45,144] Trial 78 finished with value: 0.8004150235937505 and parameters: {'n_estimators': 1800, 'learning_rate': 0.04000063271591568, 'max_depth': 3, 'subsample': 0.7557957752755619, 'colsample_bytree': 0.6155556910880398, 'gamma': 0.02387590668862277}. Best is trial 32 with value: 0.8041658262994972.
<ipython-input-134-1caae69baf53>:9: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.2),
<ipython-input-134-1caae69baf53>:11: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:12: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:13: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'gamma': trial.suggest_uniform('gamma', 0, 1),

Fold 1/5

Fold 2/5

Fold 3/5

Fold 4/5

Fold 5/5

[I 2025-04-28 15:18:48,296] Trial 79 finished with value: 0.8029256620747424 and parameters: {'n_estimators': 2000, 'learning_rate': 0.0578698385632278, 'max_depth': 5, 'subsample': 0.6996925370758855, 'colsample_bytree': 0.6408117487085836, 'gamma': 0.45793354783983775}. Best is trial 32 with value: 0.8041658262994972.
<ipython-input-134-1caae69baf53>:9: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.2),
<ipython-input-134-1caae69baf53>:11: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:12: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:13: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'gamma': trial.suggest_uniform('gamma', 0, 1),

Fold 1/5

Fold 2/5

Fold 3/5

Fold 4/5

Fold 5/5

[I 2025-04-28 15:18:51,403] Trial 80 finished with value: 0.7988550939273658 and parameters: {'n_estimators': 2000, 'learning_rate': 0.05736610889038802, 'max_depth': 7, 'subsample': 0.6636264444271468, 'colsample_bytree': 0.6669486375050139, 'gamma': 0.39141424364720073}. Best is trial 32 with value: 0.8041658262994972.
<ipython-input-134-1caae69baf53>:9: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.2),
<ipython-input-134-1caae69baf53>:11: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:12: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:13: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'gamma': trial.suggest_uniform('gamma', 0, 1),

Fold 1/5

Fold 2/5

Fold 3/5

Fold 4/5

Fold 5/5

[I 2025-04-28 15:18:58,071] Trial 81 finished with value: 0.8031559952965116 and parameters: {'n_estimators': 1900, 'learning_rate': 0.04626329047781197, 'max_depth': 5, 'subsample': 0.6823724103010661, 'colsample_bytree': 0.6017559208240272, 'gamma': 0.45515730384276826}. Best is trial 32 with value: 0.8041658262994972.
<ipython-input-134-1caae69baf53>:9: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.2),
<ipython-input-134-1caae69baf53>:11: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:12: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:13: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'gamma': trial.suggest_uniform('gamma', 0, 1),

Fold 1/5

Fold 2/5

Fold 3/5

Fold 4/5

Fold 5/5

[I 2025-04-28 15:19:01,749] Trial 82 finished with value: 0.800851202127383 and parameters: {'n_estimators': 2000, 'learning_rate': 0.04511898150118004, 'max_depth': 5, 'subsample': 0.6831500124840779, 'colsample_bytree': 0.6022153441144305, 'gamma': 0.49408190345078257}. Best is trial 32 with value: 0.8041658262994972.
<ipython-input-134-1caae69baf53>:9: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.2),
<ipython-input-134-1caae69baf53>:11: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:12: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:13: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'gamma': trial.suggest_uniform('gamma', 0, 1),

Fold 1/5

Fold 2/5

Fold 3/5

Fold 4/5

Fold 5/5

[I 2025-04-28 15:19:04,464] Trial 83 finished with value: 0.800928286193658 and parameters: {'n_estimators': 1900, 'learning_rate': 0.06766923187978471, 'max_depth': 5, 'subsample': 0.6953343237606416, 'colsample_bytree': 0.6437357901157131, 'gamma': 0.3372349401896844}. Best is trial 32 with value: 0.8041658262994972.
<ipython-input-134-1caae69baf53>:9: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.2),
<ipython-input-134-1caae69baf53>:11: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:12: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:13: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'gamma': trial.suggest_uniform('gamma', 0, 1),

Fold 1/5

Fold 2/5

Fold 3/5

Fold 4/5

Fold 5/5

[I 2025-04-28 15:19:07,066] Trial 84 finished with value: 0.7995465537728863 and parameters: {'n_estimators': 1600, 'learning_rate': 0.0808680309118776, 'max_depth': 6, 'subsample': 0.6482522814459339, 'colsample_bytree': 0.6002607000708501, 'gamma': 0.45867400390242913}. Best is trial 32 with value: 0.8041658262994972.
<ipython-input-134-1caae69baf53>:9: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.2),
<ipython-input-134-1caae69baf53>:11: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:12: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:13: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'gamma': trial.suggest_uniform('gamma', 0, 1),

Fold 1/5

Fold 2/5

Fold 3/5

Fold 4/5

Fold 5/5

[I 2025-04-28 15:19:13,667] Trial 85 finished with value: 0.8011754925451975 and parameters: {'n_estimators': 2000, 'learning_rate': 0.04867369621470002, 'max_depth': 5, 'subsample': 0.703307178996161, 'colsample_bytree': 0.6786550544077418, 'gamma': 0.5338226309253107}. Best is trial 32 with value: 0.8041658262994972.
<ipython-input-134-1caae69baf53>:9: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.2),
<ipython-input-134-1caae69baf53>:11: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:12: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:13: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'gamma': trial.suggest_uniform('gamma', 0, 1),

Fold 1/5

Fold 2/5

Fold 3/5

Fold 4/5

Fold 5/5

[I 2025-04-28 15:19:16,638] Trial 86 finished with value: 0.8027335384319956 and parameters: {'n_estimators': 1900, 'learning_rate': 0.05943602656498822, 'max_depth': 6, 'subsample': 0.6784548349396222, 'colsample_bytree': 0.6335908133790816, 'gamma': 0.4157551554584336}. Best is trial 32 with value: 0.8041658262994972.
<ipython-input-134-1caae69baf53>:9: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.2),
<ipython-input-134-1caae69baf53>:11: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:12: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:13: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'gamma': trial.suggest_uniform('gamma', 0, 1),

Fold 1/5

Fold 2/5

Fold 3/5

Fold 4/5

Fold 5/5

[I 2025-04-28 15:19:19,881] Trial 87 finished with value: 0.8019114752661405 and parameters: {'n_estimators': 1800, 'learning_rate': 0.07505630457327295, 'max_depth': 4, 'subsample': 0.738918465686214, 'colsample_bytree': 0.6508147347073967, 'gamma': 0.45568525464591947}. Best is trial 32 with value: 0.8041658262994972.
<ipython-input-134-1caae69baf53>:9: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.2),
<ipython-input-134-1caae69baf53>:11: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:12: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:13: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'gamma': trial.suggest_uniform('gamma', 0, 1),

Fold 1/5

Fold 2/5

Fold 3/5

Fold 4/5

Fold 5/5

[I 2025-04-28 15:19:27,040] Trial 88 finished with value: 0.8006605725150455 and parameters: {'n_estimators': 1700, 'learning_rate': 0.042626145189479006, 'max_depth': 5, 'subsample': 0.6017838930145978, 'colsample_bytree': 0.6391168883207431, 'gamma': 0.571618842153308}. Best is trial 32 with value: 0.8041658262994972.
<ipython-input-134-1caae69baf53>:9: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.2),
<ipython-input-134-1caae69baf53>:11: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:12: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:13: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'gamma': trial.suggest_uniform('gamma', 0, 1),

Fold 1/5

Fold 2/5

Fold 3/5

Fold 4/5

Fold 5/5

[I 2025-04-28 15:19:30,437] Trial 89 finished with value: 0.801829579337357 and parameters: {'n_estimators': 1800, 'learning_rate': 0.052759637401703606, 'max_depth': 4, 'subsample': 0.6644320442003627, 'colsample_bytree': 0.9867950996705133, 'gamma': 0.11116435187763707}. Best is trial 32 with value: 0.8041658262994972.
<ipython-input-134-1caae69baf53>:9: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.2),
<ipython-input-134-1caae69baf53>:11: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:12: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:13: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'gamma': trial.suggest_uniform('gamma', 0, 1),

Fold 1/5

Fold 2/5

Fold 3/5

Fold 4/5

Fold 5/5

[I 2025-04-28 15:19:33,444] Trial 90 finished with value: 0.7995547129571707 and parameters: {'n_estimators': 1300, 'learning_rate': 0.06369648871009266, 'max_depth': 7, 'subsample': 0.6370781373436435, 'colsample_bytree': 0.6115341943763468, 'gamma': 0.6012706408593492}. Best is trial 32 with value: 0.8041658262994972.
<ipython-input-134-1caae69baf53>:9: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.2),
<ipython-input-134-1caae69baf53>:11: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:12: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:13: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'gamma': trial.suggest_uniform('gamma', 0, 1),

Fold 1/5

Fold 2/5

Fold 3/5

Fold 4/5

Fold 5/5

[I 2025-04-28 15:19:42,161] Trial 91 finished with value: 0.8020570259311743 and parameters: {'n_estimators': 1900, 'learning_rate': 0.03125434591949628, 'max_depth': 4, 'subsample': 0.7169822059099171, 'colsample_bytree': 0.626004300519141, 'gamma': 0.9839620555061108}. Best is trial 32 with value: 0.8041658262994972.
<ipython-input-134-1caae69baf53>:9: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.2),
<ipython-input-134-1caae69baf53>:11: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:12: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:13: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'gamma': trial.suggest_uniform('gamma', 0, 1),

Fold 1/5

Fold 2/5

Fold 3/5

Fold 4/5

Fold 5/5

[I 2025-04-28 15:19:48,380] Trial 92 finished with value: 0.7986421421317728 and parameters: {'n_estimators': 2000, 'learning_rate': 0.03800746034504363, 'max_depth': 3, 'subsample': 0.699470733760254, 'colsample_bytree': 0.6219409007963942, 'gamma': 0.29434414980754514}. Best is trial 32 with value: 0.8041658262994972.
<ipython-input-134-1caae69baf53>:9: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.2),
<ipython-input-134-1caae69baf53>:11: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:12: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:13: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'gamma': trial.suggest_uniform('gamma', 0, 1),

Fold 1/5

Fold 2/5

Fold 3/5

Fold 4/5

Fold 5/5

[I 2025-04-28 15:19:56,699] Trial 93 finished with value: 0.8023140849628538 and parameters: {'n_estimators': 1900, 'learning_rate': 0.03386041161215805, 'max_depth': 4, 'subsample': 0.7319124977608238, 'colsample_bytree': 0.6597808210980427, 'gamma': 0.5062752992735828}. Best is trial 32 with value: 0.8041658262994972.
<ipython-input-134-1caae69baf53>:9: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.2),
<ipython-input-134-1caae69baf53>:11: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:12: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:13: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'gamma': trial.suggest_uniform('gamma', 0, 1),

Fold 1/5

Fold 2/5

Fold 3/5

Fold 4/5

Fold 5/5

[I 2025-04-28 15:20:00,182] Trial 94 finished with value: 0.800590348063365 and parameters: {'n_estimators': 2000, 'learning_rate': 0.04685584433766505, 'max_depth': 5, 'subsample': 0.7784922146454485, 'colsample_bytree': 0.6833640322226546, 'gamma': 0.36722441400126166}. Best is trial 32 with value: 0.8041658262994972.
<ipython-input-134-1caae69baf53>:9: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.2),
<ipython-input-134-1caae69baf53>:11: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:12: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:13: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'gamma': trial.suggest_uniform('gamma', 0, 1),

Fold 1/5

Fold 2/5

Fold 3/5

Fold 4/5

Fold 5/5

[I 2025-04-28 15:20:08,981] Trial 95 finished with value: 0.8019445904260254 and parameters: {'n_estimators': 1800, 'learning_rate': 0.029767645915049625, 'max_depth': 6, 'subsample': 0.615590625472055, 'colsample_bytree': 0.6139062056628448, 'gamma': 0.03430139586377845}. Best is trial 32 with value: 0.8041658262994972.
<ipython-input-134-1caae69baf53>:9: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.2),
<ipython-input-134-1caae69baf53>:11: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:12: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:13: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'gamma': trial.suggest_uniform('gamma', 0, 1),

Fold 1/5

Fold 2/5

Fold 3/5

Fold 4/5

Fold 5/5

[I 2025-04-28 15:20:15,353] Trial 96 finished with value: 0.8022577825846744 and parameters: {'n_estimators': 1600, 'learning_rate': 0.024156718751326304, 'max_depth': 5, 'subsample': 0.7207266103082108, 'colsample_bytree': 0.666997493756482, 'gamma': 0.4370367872620956}. Best is trial 32 with value: 0.8041658262994972.
<ipython-input-134-1caae69baf53>:9: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.2),
<ipython-input-134-1caae69baf53>:11: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:12: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:13: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'gamma': trial.suggest_uniform('gamma', 0, 1),

Fold 1/5

Fold 2/5

Fold 3/5

Fold 4/5

Fold 5/5

[I 2025-04-28 15:20:27,315] Trial 97 finished with value: 0.8017207123010422 and parameters: {'n_estimators': 1500, 'learning_rate': 0.02078601198054215, 'max_depth': 4, 'subsample': 0.8086397582446112, 'colsample_bytree': 0.6520030051476806, 'gamma': 0.0641847913215688}. Best is trial 32 with value: 0.8041658262994972.
<ipython-input-134-1caae69baf53>:9: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.2),
<ipython-input-134-1caae69baf53>:11: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:12: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:13: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'gamma': trial.suggest_uniform('gamma', 0, 1),

Fold 1/5

Fold 2/5

Fold 3/5

Fold 4/5

Fold 5/5

[I 2025-04-28 15:20:36,383] Trial 98 finished with value: 0.7991423803892884 and parameters: {'n_estimators': 1900, 'learning_rate': 0.04169178876377865, 'max_depth': 3, 'subsample': 0.7968932738937696, 'colsample_bytree': 0.698932128553263, 'gamma': 0.8792529513798195}. Best is trial 32 with value: 0.8041658262994972.
<ipython-input-134-1caae69baf53>:9: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 0.01, 0.2),
<ipython-input-134-1caae69baf53>:11: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'subsample': trial.suggest_uniform('subsample', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:12: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'colsample_bytree': trial.suggest_uniform('colsample_bytree', 0.6, 1.0),
<ipython-input-134-1caae69baf53>:13: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'gamma': trial.suggest_uniform('gamma', 0, 1),

Fold 1/5

Fold 2/5

Fold 3/5

Fold 4/5

Fold 5/5

[I 2025-04-28 15:20:38,123] Trial 99 finished with value: 0.7968905902300708 and parameters: {'n_estimators': 100, 'learning_rate': 0.05639657060353712, 'max_depth': 4, 'subsample': 0.7485310395093112, 'colsample_bytree': 0.8404840004797264, 'gamma': 0.21168520861294043}. Best is trial 32 with value: 0.8041658262994972.

Best hyperparameters found:  {'n_estimators': 1400, 'learning_rate': 0.04931476093184571, 'max_depth': 4, 'subsample': 0.6578843387359619, 'colsample_bytree': 0.6902394255031622, 'gamma': 0.11174367093570015}
Best F1 score:  0.8041658262994972

In [135]:
study.best_params

{'n_estimators': 1400,
 'learning_rate': 0.04931476093184571,
 'max_depth': 4,
 'subsample': 0.6578843387359619,
 'colsample_bytree': 0.6902394255031622,
 'gamma': 0.11174367093570015}